### PR TITLE
[Spec2Vec] Including Spec2Vec Workflow in GNPS

### PR DESCRIPTION
**Pull request by mwang87**

### CODE REVIEW

**Comment by mwang87** [comment]
Test Examples

| Title  | GNPS Task Original | GNPS Reruns  | Spec2Vec Task  |
|---|---|---|---|
| MFuser_BioCorrected_SPLIT   | [Link](https://gnps.ucsd.edu/ProteoSAFe/status.jsp?task=26326c233918419f8dc80e8af984cdae)   | [Link](https://gnps.ucsd.edu/ProteoSAFe/status.jsp?task=c6f34d5b54bf47b584f33e88fea03f5d) | [Link]()  |

**Comment by justinjjvanderhooft** [comment]
Working rerun of the Crusemann dataset (SalStrep) - -> https://gnps.ucsd.edu/ProteoSAFe/status.jsp?task=9bc1bfb0c18f4f16b56e32c8058225e7

**Comment by justinjjvanderhooft** [comment]
Ming, did you check the name of the edge column that contains the Spec2Vec scores? It would be good to call that "Spec2Vec" or something alike to make it different from the cosine score. Now, in the filtered results, it is called cosine, which may be a bit confusing.

**Comment by robinschmid** [comment]
One question are you combining the cosine score networking with Spec2Vec? In this case you could just use the generic names
EdgeType=Spec2Vec
EdgeScore= ...
EdgeAnnotation= ...

This would make it compatible with the ion identity networking style and the supplementary edges format

**Comment by justinjjvanderhooft** [comment]
Good point @robinschmid - of course we want to make it compatible with other edge formats - also to make it generic. I browsed a bit further into the results in CytoScape:
Schermafbeelding 2020-12-09 om 11 59 37
In the filtered results (so all cosine connections are filtered out - which is the default option), all edgeTypes are indeed Spec2Vec. The possible confusion could come from the "cosine score" column, which is still present, but I think that this cannot be easily solved as it is a prerequisite column. The EdgeScore and cosine score seem to be copies of each other. You can see that the number corresponds to the "EdgeScore", which is indeed the Spec2Vec score. That was my main remark regarding a possible source of confusion for users. 
In the non-filtered results, we see both cosine and Spec2Vec types:
Schermafbeelding 2020-12-09 om 11 53 20
Schermafbeelding 2020-12-09 om 11 53 33
In the networks here, some connections are Spec2Vec, and others are cosine. I am assuming we only keep the highest score here @mwang87? Would be good to explain what happens there? Also, I noted that some nodes have self-loop edges of the cosine score of 1 - any idea where they come from? Since this is not the default option and it will take some time, I think we could leave it like this for V27 and further work on it during V28 and future iterations?

**Comment by robinschmid** [comment]
Self loops for singletons are most likely added based solely on FBMN. So if no cosine score is > threshold it gets a self loop. I see similar things happening for other additional edges

Without looking at the code - I guess ming is only keeping the edge with the highest score.

**Comment by justinjjvanderhooft** [comment]
Thanks @robinschmid - good point re self-loops - actually, you have them as well in classical molecular networking (the above two network screenshots are from a classical molecular network) - there are some self loops that are in the combined network (non-filtered for cosine scores) - this would mean that these are nodes that are now part of a family due to the Spec2Vec scoring. Interesting....

And re highest scoring - I tend to agree, but then I wonder why/how the a node in the network can have both a self-loop and a connection - anyways, this would be the preferred lay-out as otherwise the connection (being less than score 1) would be gone....

**Comment by mwang87** [comment]
> One question are you combining the cosine score networking with Spec2Vec? In this case you could just use the generic names
> EdgeType=Spec2Vec
> EdgeScore= ...
> EdgeAnnotation= ...
> 
> This would make it compatible with the ion identity networking style and the supplementary edges format

Yes, we have it fully compatible with exactly those fields.

**Comment by mwang87** [comment]
> Ming, did you check the name of the edge column that contains the Spec2Vec scores? It would be good to call that "Spec2Vec" or something alike to make it different from the cosine score. Now, in the filtered results, it is called cosine, which may be a bit confusing.

Names are updated now on output display. Deployed latest spec2vec version after merging.

**Comment by mwang87** [comment]
@justinjjvanderhooft I think we'd keep the default top k edges as is right now for release 27. I think we'll want to start pruning the self edges as those should have been removed but likely were not. We can tackle that in release 28 as that likely won't cause a big deal in visualizing the data.

**Comment by justinjjvanderhooft** [comment]
Agreed @mwang87 - I think we are on the same page - it is good to be aware of this now! 😎

**Comment by justinjjvanderhooft** [comment]
@mwang87 rerunning MFuser_BioCorrected_SPLIT in release 27 now throws up an error - please find the link to a job here:
https://gnps.ucsd.edu/ProteoSAFe/status.jsp?task=6fb158248f08457f88612f561712ab59

and a copy of the error:

Parallel to execute 1
Error tempresults/spec-00000.mgf.summary
/data/ccms-gnps/tools/metabolomicsnetsv2/release_27/scripts/msaccess inputspectra/spec-00000.mgf -x "run_summary delimiter=tab" > tempresults/spec-00000.mgf.summary
Traceback (most recent call last):
  File "/data/ccms-gnps/tools/metabolomicsnetsv2/release_27/scripts/filesummary.py", line 113, in <module>
    main()
  File "/data/ccms-gnps/tools/metabolomicsnetsv2/release_27/scripts/filesummary.py", line 105, in main
    result_object["CCMS_filename"] = os.path.basename(full_path)
UnboundLocalError: local variable 'result_object' referenced before assignment
Tool execution terminates abnormally with exit code [1]

**Comment by justinjjvanderhooft** [comment]
@mwang87 rerunning MFuser_BioCorrected_SPLIT in release 27 now throws up an error - please find the link to a job here:
https://gnps.ucsd.edu/ProteoSAFe/status.jsp?task=6fb158248f08457f88612f561712ab59

and a copy of the error:

**Comment by justinjjvanderhooft** [comment]
All other jobs run fine - also the Spec2Vec network analysis! :-)

**Pull request merged**
