### PR TITLE
 Adding DEREPLICATOR linkout in V2

### PR DESCRIPTION
**Pull request by lfnothias**
I tried to make these linkout. I guessed the spec_net param since the DEREPLICATOR workflows are not public, so this will have to be checked.

### CODE REVIEW

**Comment by mwang87** [comment]
Can you check with Alexey about parameter names before commiting this?

**Comment by lfnothias** [comment]
Hey @alexeigurevich,
Can you let me know if the parameter name is the correct for Dereplicator and Dereplicator+ ?
Also you have the proteosafe workflows available somewhere, so I can include more parameters in the linkout ?

**Comment by alexeigurevich** [comment]
Hi Louis, I've just added you to the NPDtools private repo, please check that you have access to e.g. `https://github.com/ablab/dereplicator/blob/master/ProteoSAFe/workflows/dereplicator_plus/`. I hope everything you need is there.

As for the primary topic. Are you talking about parameters you used here?
`<parameter name="URLBASE" value='https://gnps.ucsd.edu/ProteoSAFe/index.jsp?params={"workflow":"DEREPLICATOR_PLUS:1.0.0", "desc":"DEREPLICATOR+ of Classic Molecular Networking V2 [task]", "spec_on_server":"t.[task]/spectra/specs_ms.mgf"}'/>`

I am not sure about the syntax, e.g. how this `"workflow"` part should be infered based on my .xml configuration files. E.g. my `input.xml` contains:
```
<interface id="dereplicating-plus" version="1.0.0">
    <workflow-id>dereplicator_plus</workflow-id>
    <workflow-label>Dereplicator+</workflow-label>
```
I assume this means that your `"workflow"` is correct (the same for regular Dereplicator as well).

**Comment by mwang87** [comment]
This should be thanks @alexeigurevich! We're going to link to spec_on_server which we've already done and will update the workflow name so people can reanalyze their networks with a single click.

**Pull request merged**
