### PR TITLE
[FBMN] More flexible conversion script for Optimus

### PR DESCRIPTION
**Pull request by lfnothias**
The previous script had metadata group requirements that were specific to the input test file.

### CODE REVIEW

**Comment by lfnothias** [comment]
@mwang87 ready for review

**Comment by mwang87** [comment]
I think this PR got mixed with the sirius one. Might need to clean up

**Comment by lfnothias** [comment]
Sorry about getting mixed with the PRs. I assumed it was already merged because there has been a release. Next time will be more careful. Hopefully that is okay because these are minor changes.

**Comment by lfnothias** [comment]
Closing this PR in favor of a most recent PR #667 that includes this feature.

**Pull request closed without merging**
