### PR TITLE
Adding Qiime2 into GC Workflow

### PR DESCRIPTION
**Pull request by mwang87**

### CODE REVIEW

**Comment by mwang87** [comment]
Tested here: https://proteomics3.ucsd.edu/ProteoSAFe/status.jsp?task=10a3a745fdf046cfaa766198da86d72a

Ready to merge.

**Comment by aaksenov1** [comment]
Noticed the masses are shifted by .2 again in all recent jobs.

**Comment by mwang87** [comment]
Noted. Can you address main feature for this?

**Comment by aaksenov1** [comment]
Will do

**Pull request merged**
