### PR TITLE
[FBMN] Update to the OpenMS formatter

### PR DESCRIPTION
**Pull request by lfnothias**
Fix the FBMN (OpenMS) workflow when duplicated filenames are in the input.
If duplicated filename exists in the input, only the first occurence is conserved in the output.

### CODE REVIEW

**Comment by lfnothias** [comment]
@mwang87 please give me headsup when deploy. This job should be resolved with this fix: https://gnps.ucsd.edu/ProteoSAFe/status.jsp?task=ce5daa945eac47939daf413519835ca3

**Comment by mwang87** [comment]
Looks good, will deploy to Proteomics2 soon and add to test suite.

**Comment by lfnothias** [comment]
@mwang87 Running the job here:
https://proteomics2.ucsd.edu/ProteoSAFe/status.jsp?task=31d2c84a03524dd79c589f2b1a966e7f

**Comment by lfnothias** [comment]
The job ran successfully !

**Pull request merged**
