### PR TITLE
[FBMN] Fix for Progenesis QI with IMS

### PR DESCRIPTION
**Pull request by lfnothias**
Fixing support for CSS
Adding new columns to the converted table.
Should fix and use #281 as test job

### CODE REVIEW

**Comment by lfnothias** [comment]
@mwang87 Can you remind me how to run the test jobs locally ?

**Comment by lfnothias** [comment]
The test are good except for that error. But I haven't changed the code, and the script works fine in my env, so I am not sure.
Traceback (most recent call last): File "/Github/GNPS_Workflows/feature-based-molecular-networking/test/test_converters.py", line 30, in test_progenesis "./progenesis_MSE_output.csv") File "../tools/feature-based-molecular-networking/scripts/progenesis_formatter.py", line 32, in convert_to_feature_csv compound_name = record["Compound"] KeyError: 'Compound'

**Comment by mwang87** [comment]
OK, we'll have to take a look. All the test cases should pass. A code change likely broke something. The tests seem to be doing their job though.

**Comment by mwang87** [comment]
It seems you overwrote a lot of files that shoudln't have been overwritten. Specifically the input files. Can you look at these and be careful of what you overwrote? 

You basically overwrote an input as your own output.

**Comment by lfnothias** [comment]
I provided new reference output files for the Progenesis QI test because they have changed (new columns). 
I looked at the tests and it looks okay to me, but they still don't pass for progenesis.
Also, do you have reference output .MGF files for progenesis ?

**Comment by lfnothias** [comment]
I pushed my last changes. The only error for the converters is:
Traceback (most recent call last):
` File "/Github/GNPS_Workflows/feature-based-molecular-networking/test/test_converters.py", line 54, in test_progenesis
    progenesis_formatter.convert_mgf("./reference_input_file_for_formatter/Progenesis/161118_pos_IMS.msp", "progenesis_output_IMS.mgf", compound_to_scan_mapping)
  File "../tools/feature-based-molecular-networking/scripts/progenesis_formatter.py", line 87, in convert_mgf
    output_filename.write("SCANS=%s\n" % (compound_to_scan_mapping[compound_name]))
KeyError: 'Decanoate'
`

**Pull request closed without merging**
