### PR TITLE
BUG: Removing iTOL in favor of Empress

### PR DESCRIPTION
**Pull request by mwang87**

### CODE REVIEW

**Comment by mwang87** [comment]
Testing here: https://proteomics2.ucsd.edu/ProteoSAFe/status.jsp?task=e3271745188f4379acae2b23f2f26e2d

**Comment by anupriyatripathi** [comment]
@mwang87 thanks for running the tests - looks like they are not producing the expected output yet. Can we access the run logs for these to debug?

https://proteomics2.ucsd.edu/ProteoSAFe/status.jsp?task=e3271745188f4379acae2b23f2f26e2d
https://proteomics2.ucsd.edu/ProteoSAFe/status.jsp?task=1dfe3088c1f24d208f16356522f504df
https://proteomics2.ucsd.edu/ProteoSAFe/status.jsp?task=a1ee0f34666247cea89f6e4fea69bf72

**Comment by mwang87** [comment]
> @mwang87 thanks for running the tests - looks like they are not producing the expected output yet. Can we access the run logs for these to debug?
> 
> https://proteomics2.ucsd.edu/ProteoSAFe/status.jsp?task=e3271745188f4379acae2b23f2f26e2d
> https://proteomics2.ucsd.edu/ProteoSAFe/status.jsp?task=1dfe3088c1f24d208f16356522f504df
> https://proteomics2.ucsd.edu/ProteoSAFe/status.jsp?task=a1ee0f34666247cea89f6e4fea69bf72

These are old test jobs, here is a new one:

https://proteomics2.ucsd.edu/ProteoSAFe/status.jsp?task=207e8fd0edaa45309660b72cfddd050c

**Comment by mwang87** [comment]
Adding new test job with the debugging PR from @anupriyatripathi 

[Link](https://proteomics2.ucsd.edu/ProteoSAFe/status.jsp?task=9ffe70d5b3a74504b79c6bb9cbd33359)

**Comment by anupriyatripathi** [comment]
Thanks @mwang87 for adding the missing flag. [Link to test job](https://proteomics2.ucsd.edu/ProteoSAFe/status.jsp?task=26dd504c59d7406899ddcb8d7dade505)

**Comment by anupriyatripathi** [comment]
@mwang87 @ElDeveloper I am also able to run empress locally successfully with the files generated from [this test job](https://proteomics2.ucsd.edu/ProteoSAFe/status.jsp?task=26dd504c59d7406899ddcb8d7dade505) which has the latest changes including the flag `--p-filter-missing-features`. It still fails on the GNPS server for some reason. Could it be a version issue? I am running `qiime2-2020.11 ` and the latest releases of empress and qemistree.

**Comment by ElDeveloper** [comment]
Good point! It might be the qemistree version in the GNPS machine. That might 
explain why the transformer is not being applied and in turn the index name 
problem shows up.

**Comment by mwang87** [comment]
So is the version we should be using qiime2-2020.11? 

If so I can revise all documentation and runtime to that effect.

**Comment by ElDeveloper** [comment]
I thin the qemistree version is more critical than the QIIME2 version.

Thanks!

Yoshiki

**Pull request merged**
