### PR TITLE
mzmine validator tester

### PR DESCRIPTION
**Pull request by cmaceves**

### CODE REVIEW

**Comment by cmaceves** [comment]
addressing issue #364

**Comment by mwang87** [comment]
Is the function validate_mzmine_output_file being used in the actual code? I can add, but doesn't appear to be used currently.

**Comment by cmaceves** [comment]
> Is the function validate_mzmine_output_file being used in the actual code? I can add, but doesn't appear to be used currently.

I'm unsure if it's currently a part of the workflow (I didn't add it), I just wrote the function into the file!

**Comment by mwang87** [comment]
Cool sounds good. Let me merge it into a branch and I'll plug it into the workflow.

**Comment by mwang87** [comment]
Merging into branch

**Pull request merged**
