### PR TITLE
Molnetenhancer ms2ldaintegration

### PR DESCRIPTION
**Pull request by mwang87**

### CODE REVIEW

**Comment by mwang87** [comment]
@laserc Could you take a look at this? I think we might need to resolve some of the conflicts, it you could pull master into your branch and resolve them. I think it might have been my fault as I tried to make some changes. Sorry!

**Comment by mwang87** [comment]
@laserc Hmm there still seems to be conflicts in the merge.

**Comment by laserc** [comment]
How do I resolve conflicts in these files locally?

**Comment by mwang87** [comment]
They have a commandline instructions you can click on below that shows you the commands you'll need to use.

**Comment by laserc** [comment]
conflicts resolved locally
git commit
can't git push because no access

**Comment by mwang87** [comment]
Added you as collaborator on this repo. should be able to push now.

**Comment by laserc** [comment]
Okay pushed the conflict resolutions. Master branch should be up to date with molnetenhancer_ms2ldaintegration branch so the next merge can be automatic. Next: pushing minor syntax changes to molnetenhancer_ms2ldaintegration branch

**Comment by mwang87** [comment]
Awesome! Let me know when you're done with that and we can do a deployment to proteomics2 and test it out!

Ming

**Comment by laserc** [comment]
github isn't detecting a difference in this function of chemClass2Network.py 

molnetenhancer_ms2ldaintegration branch:
`def request_Varquest_file(Varquest_job_ID, directory):`
....
 `  zf = ZipFile(BytesIO(result.content))`
 `  folder_name = directory + '/Varquest_output'`
 `  zf.extractall(folder_name)`
 `  zf.close()`
 `  return folder_name;`

master:
`def request_Varquest_file(Varquest_job_ID):`
....
`   zf = ZipFile(BytesIO(result.content))`
`    zf.extractall('Varquest_output')`
`    zf.close()`
`    return folder_name;`

**Pull request merged**
